// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEA0SOBkoxjcf4abbeTZ7zxiUvm2tgl0c',
    appId: '1:721383561915:web:4b65c69150e5301d2ca79e',
    messagingSenderId: '721383561915',
    projectId: 'hoomy-267dd',
    authDomain: 'hoomy-267dd.firebaseapp.com',
    storageBucket: 'hoomy-267dd.firebasestorage.app',
    measurementId: 'G-8X7PWQN6QB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBXked-jfDEa6LAUJd6k3BBQHhVDhCPShU',
    appId: '1:721383561915:android:067002e1d0ff23a12ca79e',
    messagingSenderId: '721383561915',
    projectId: 'hoomy-267dd',
    storageBucket: 'hoomy-267dd.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBl8N-eHwxXaG5d2Q2ubfKWfMV7n2A1td0',
    appId: '1:721383561915:ios:e43699908d70a5432ca79e',
    messagingSenderId: '721383561915',
    projectId: 'hoomy-267dd',
    storageBucket: 'hoomy-267dd.firebasestorage.app',
    iosBundleId: 'com.idea.hoomy.hoomy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEA0SOBkoxjcf4abbeTZ7zxiUvm2tgl0c',
    appId: '1:721383561915:web:2871d6e5088328802ca79e',
    messagingSenderId: '721383561915',
    projectId: 'hoomy-267dd',
    authDomain: 'hoomy-267dd.firebaseapp.com',
    storageBucket: 'hoomy-267dd.firebasestorage.app',
    measurementId: 'G-C6G0GFYH9E',
  );
}
