import 'package:flutter/widgets.dart';

class AppLocalizations {
  final Locale locale;

  const AppLocalizations(this.locale);

  static const supportedLocales = [Locale('en'), Locale('ar')];

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        const AppLocalizations(Locale('en'));
  }

  String get languageCode => locale.languageCode;
  String get localeName => languageCode == 'ar' ? 'ar' : 'en';
  bool get isArabic => languageCode == 'ar';

  String t(String key) {
    final english = _strings['en']!;
    return (_strings[languageCode] ?? english)[key] ?? english[key] ?? key;
  }

  String tr(String key, Map<String, Object?> values) {
    var value = t(key);
    for (final entry in values.entries) {
      value = value.replaceAll('{${entry.key}}', entry.value.toString());
    }
    return value;
  }

  String relation(String value) {
    return switch (value.toLowerCase()) {
      'you' => t('relationYou'),
      'father' => t('relationFather'),
      'mother' => t('relationMother'),
      'brother' => t('relationBrother'),
      'sister' => t('relationSister'),
      'son' => t('relationSon'),
      'daughter' => t('relationDaughter'),
      'grandfather' => t('relationGrandfather'),
      'grandmother' => t('relationGrandmother'),
      'grandson' => t('relationGrandson'),
      'granddaughter' => t('relationGranddaughter'),
      'uncle' => t('relationUncle'),
      'aunt' => t('relationAunt'),
      'cousin' => t('relationCousin'),
      'nephew' => t('relationNephew'),
      'niece' => t('relationNiece'),
      'guest' => t('relationGuest'),
      'member' || '' => t('member'),
      _ => value,
    };
  }
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) {
    return AppLocalizations.supportedLocales
        .any((item) => item.languageCode == locale.languageCode);
  }

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}

extension AppLocalizationsX on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}

const _strings = {
  'en': {
    'language': 'Language',
    'languageInfo': 'Choose the app language on this phone.',
    'english': 'English',
    'arabic': 'Arabic',
    'hoomy': 'Hoomy',
    'gettingHomeReady': 'Getting your home ready...',
    'authSubtitle':
        'Shared home needs, family alerts, reminders, and quick actions.',
    'phone': 'Phone',
    'email': 'Email',
    'childAccountName': 'Child account name',
    'yourName': 'Your name',
    'phoneNumber': 'Phone number',
    'emailAddress': 'Email address',
    'password': 'Password',
    'forgotPassword': 'Forgot password?',
    'signInAsChild': 'Sign in as child account',
    'stillYoungChild': 'Still young / child account',
    'useUniqueChildName': 'Use the unique child name.',
    'noPhoneEmailChild':
        'No phone or email required. A parent can manage this account.',
    'connecting': 'Connecting',
    'signIn': 'Sign in',
    'continue': 'Continue',
    'createNewAccount': 'Create new account',
    'alreadyHaveAccount': 'Already have an account? Sign in',
    'resetPassword': 'Reset password',
    'resetRequestSent': 'Reset request sent. Saving the new password now.',
    'resetting': 'Resetting',
    'home': 'Home',
    'chat': 'Chat',
    'calendar': 'Calendar',
    'settings': 'Settings',
    'joinHouse': 'Join house',
    'createHouse': 'Create house',
    'createNewHouse': 'Create new house',
    'defaultHouseName': 'Our home',
    'couldNotCreateHouse': 'Could not create house',
    'chooseHouse': 'Choose house',
    'chooseHouseTitle': 'Which house do you want to enter?',
    'chooseHouseBody':
        'This account belongs to more than one house. Choose the active house for this session.',
    'chooseFromMyHouses': 'Choose from my houses',
    'joinAHouse': 'Join a house',
    'createYourHouse': 'Create your house',
    'signOut': 'Sign out',
    'create': 'Create',
    'join': 'Join',
    'yourFamilyRole': 'Your family role',
    'houseSpecialNumber': 'House special number',
    'scanHouseQr': 'Scan house QR',
    'houseName': 'House name',
    'addressOrNeighborhood': 'Address or neighborhood',
    'allowHouseLocation': 'Allow house location',
    'usedOutsideMembers':
        'Used later to alert members who are outside the house first.',
    'currentLocation': 'Current location',
    'gettingCurrentLocation': 'Getting current location...',
    'noLocationAdded': 'No location added',
    'enableLocation': 'Enable location',
    'enableLocationBody':
        'Turn on device location, then allow Hoomy to use your current location.',
    'enableStatusLocationBody':
        'Turn on device location, then allow Hoomy to update your house status.',
    'enableHouseLocationBody':
        'Turn on device location, then allow Hoomy to save this phone location as the house location.',
    'enableAutoStatusLocationBody':
        'Turn on device location, then allow Hoomy to update your house status automatically.',
    'ok': 'OK',
    'couldNotGetLocation':
        'Could not get current location. Check location services and permission.',
    'currentLocationAdded': 'Current location added to this house.',
    'joining': 'Joining',
    'creating': 'Creating',
    'familyChat': 'Family chat',
    'noMessagesYet': 'No messages yet',
    'messagePending': 'Pending',
    'messageSent': 'Sent',
    'messageReceived': 'Received',
    'messageSeen': 'Seen',
    'messageFailed': 'Failed',
    'member': 'Member',
    'messageTheFamily': 'Message the family',
    'attachImage': 'Attach image',
    'captureImage': 'Take photo',
    'saveImage': 'Save image',
    'imageSavedToPhone': 'Image saved to your phone',
    'couldNotSaveImage': 'Could not save image',
    'couldNotSendMessage': 'Could not send message',
    'messageOptions': 'Message options',
    'reply': 'Reply',
    'replyToYourMessage': 'Add a follow-up to your message',
    'replyToFamilyMessage': 'Reply in the family chat',
    'replyingTo': 'Replying to {name}',
    'cancelReply': 'Cancel reply',
    'edit': 'Edit',
    'editYourMessage': 'Update the text you sent',
    'info': 'Info',
    'viewMessageInfo': 'See who received or read it',
    'messageInfo': 'Message info',
    'sentAt': 'Sent at {time}',
    'readBy': 'Read by',
    'deliveredTo': 'Delivered to',
    'read': 'Read',
    'delivered': 'Delivered',
    'notSeenYet': 'No one has read it yet.',
    'notDeliveredYet': 'No delivery confirmation yet.',
    'reactions': 'Reactions',
    'removeReaction': 'Remove my reaction',
    'couldNotReactMessage': 'Could not update reaction',
    'edited': 'Edited',
    'editingMessage': 'Editing message',
    'cancelEdit': 'Cancel edit',
    'couldNotEditMessage': 'Could not edit message',
    'recordVoiceMessage': 'Record voice message',
    'holdToRecord': 'Hold to record',
    'sendVoiceMessage': 'Send voice message',
    'slideLeftToCancel': 'Slide left to cancel',
    'releaseToCancel': 'Release to cancel',
    'slideUpToLock': 'Lock',
    'recordingLocked': 'Recording locked',
    'stopRecording': 'Stop recording',
    'voicePreview': 'Voice preview',
    'playVoicePreview': 'Play voice preview',
    'voiceMessageSeconds': 'Voice message â€¢ {seconds}s',
    'playbackSpeed': 'Playback speed',
    'microphonePermissionDenied': 'Microphone permission is needed to record.',
    'microphoneReadyHoldAgain':
        'Microphone is ready. Hold the mic again to record.',
    'couldNotRecordMessage': 'Could not start recording.',
    'couldNotSendVoiceMessage': 'Could not send voice message',
    'couldNotSendImageMessage': 'Could not send image',
    'thisMonth': 'This month',
    'needAlert': 'Need alert',
    'urgent': 'Urgent',
    'addMember': 'Add member',
    'quickActions': 'Quick actions',
    'quickActionsInfo':
        'Keep your most-used family actions close, like calling home, opening SMS, or sending a quick chat message.',
    'add': 'Add',
    'needsAlerts': 'Needs alerts',
    'needsAlertsInfo':
        'Share the little things the house needs before anyone forgets. Mark it urgent when it truly needs quick attention.',
    'new': 'New',
    'cancel': 'Cancel',
    'clearSelection': 'Clear selection',
    'selectNeeds': 'Select needs',
    'boughtCount': 'Done ({count})',
    'noMissingItems': 'No missing items right now.',
    'reminders': 'Reminders',
    'remindersInfo':
        'A shared place for family tasks, dates, and house moments everyone should remember.',
    'family': 'Family',
    'familyInfo':
        'See your family members, how they relate to you, and who is currently inside or outside the house.',
    'memberLocation': 'Member location',
    'viewMemberLocation': 'View member location',
    'locationNotAvailable': 'Location is not available yet.',
    'locationNotAvailableBody':
        'This member has not shared a current location from Hoomy yet.',
    'latitude': 'Latitude',
    'longitude': 'Longitude',
    'lastUpdated': 'Last updated',
    'notUpdatedYet': 'Not updated yet',
    'openGoogleMaps': 'Open Google Maps',
    'invite': 'Invite',
    'helloName': 'Hello, {name}',
    'homeSummary':
        '{needs} open needs, {reminders} reminders, {members} members.',
    'birthdayToday': 'Birthday today: {name}',
    'birthdaysToday': 'Birthdays today: {names}',
    'outside': 'Outside',
    'inside': 'Inside',
    'updatedOutside': 'Updated: outside the house.',
    'updatedInside': 'Updated: inside the house.',
    'couldNotUpdateLocationStatus': 'Could not update location status.',
    'markSelectedNeedsBought': 'Mark selected needs as done',
    'notifyFamily': 'Notify family',
    'notifying': 'Notifying...',
    'couldNotNotifyFamily': 'Could not notify family',
    'quantityOptional': 'Quantity optional',
    'priceOptional': 'Price optional',
    'markAsBought': 'Mark {item} as done',
    'bought': 'Done',
    'house': 'House',
    'houseInfo':
        'This is your family space. Keep the house address and special join number here for the people you trust.',
    'noAddressAdded': 'No address added',
    'changeHouse': 'Change house',
    'changeHouseSubtitle': 'Join another house by special number or QR.',
    'changeHouseInfo':
        'You will stay as a member of the old house, but your status will become outside until you enter the active house and update your location.',
    'changeHouseQuestion': 'Change to this house?',
    'changeHouseConfirmBody':
        'Hoomy will switch your active house to this special number. You will stay in the old house and be marked outside until your location is updated.',
    'changingHouse': 'Changing house...',
    'houseChanged': 'House changed. You are marked outside for now.',
    'enterHouseSpecialNumber': 'Enter the house special number.',
    'couldNotChangeHouse': 'Could not change house',
    'showQrCode': 'Show QR code',
    'copySpecialNumber': 'Copy special number',
    'location': 'Location',
    'locationInfo':
        'Location helps the family know when you are around home, only when you choose to allow it.',
    'notifications': 'Notifications',
    'about': 'About',
    'aboutInfo':
        'A quiet corner for app details, realtime connection status, and future house features.',
    'account': 'Account',
    'accountInfo':
        'Manage your session on this device. Signing out keeps your account ready for the next time.',
    'profile': 'Profile',
    'editProfile': 'Edit profile',
    'fullName': 'Full name',
    'birthday': 'Birthday',
    'noPhoneAdded': 'No phone added',
    'noEmailAdded': 'No email added',
    'tapToChooseBirthday': 'Tap to choose birthday',
    'saveProfile': 'Save profile',
    'profileSaved': 'Profile saved',
    'couldNotSaveProfile': 'Could not save profile',
    'nameRequired': 'Name is required',
    'yourBirthday': 'Your birthday',
    'noBirthdayAdded': 'No birthday added',
    'removeBirthday': 'Remove birthday',
    'birthdayRemoved': 'Birthday removed',
    'birthdaySaved': 'Birthday saved',
    'couldNotSaveBirthday': 'Could not save birthday',
    'houseLocation': 'House location',
    'noHouseLocationSaved': 'No house location saved.',
    'houseLocationSaved': 'House location is saved.',
    'myStatus': 'My status',
    'signInToUpdateStatus': 'Sign in to update your status.',
    'update': 'Update',
    'autoUpdateStatus': 'Auto update status',
    'saveHouseLocationFirst': 'Save the house location first.',
    'refreshStatusEveryFew': 'Refresh inside/outside status every few minutes.',
    'familyChatMessages': 'Family chat messages',
    'notificationsInfo':
        'Choose the family updates this phone should receive, including alerts while Hoomy is not open.',
    'showMissingItemAlerts': 'Show missing item alerts.',
    'useLongerEmergencySound': 'Use the longer emergency sound.',
    'notifyChatNew': 'Notify when chat has something new.',
    'pushStatus': 'Push status',
    'needAlertsSetting': 'Need alerts',
    'emergencyAlerts': 'Emergency alerts',
    'emergencyAlertCount': '{count} emergency alerts',
    'shortcuts': 'Shortcuts',
    'shortcutsInfo':
        'Make small family routines faster with personal shortcuts for calls, SMS, and chat messages.',
    'noShortcutsYet': 'No shortcuts yet',
    'updateShortcut': 'Update shortcut',
    'deleteShortcut': 'Delete shortcut',
    'updateReminder': 'Update reminder',
    'deleteReminder': 'Delete reminder',
    'autoMembersOutside': 'Auto: members outside house',
    'requestFailed': 'Request failed',
    'deleteShortcutQuestion': 'Delete shortcut?',
    'deleteShortcutBody': 'Delete "{label}" from your shortcuts?',
    'delete': 'Delete',
    'couldNotDeleteShortcut': 'Could not delete shortcut',
    'viewAll': 'View all',
    'futureHouseDiscovery': 'Future house discovery',
    'privateHousesNow': 'Private houses now, ready to expand later.',
    'realtimeBackend': 'Realtime backend',
    'restSocketEnabled': 'REST and Socket.IO sync are enabled.',
    'aboutHoomy': 'About Hoomy',
    'aboutHoomyBody':
        'Hoomy helps the family keep the house moving together: needs, alerts, reminders, chat, location status, and quick actions in one calm place.',
    'aboutNeedsTitle': 'House needs',
    'aboutNeedsBody':
        'Add missing items and let the family know when someone buys them.',
    'aboutAlertsTitle': 'Smart alerts',
    'aboutAlertsBody':
        'Send normal or emergency alerts to everyone or selected members.',
    'aboutChatTitle': 'Family chat',
    'aboutChatBody':
        'Keep simple family messages and house updates in the same place.',
    'aboutCalendarTitle': 'Shared calendar',
    'aboutCalendarBody':
        'See reminders, birthdays, and house events in a clear calendar view.',
    'appVersion': 'App version',
    'currentVersion': 'Current version: {version}',
    'latestVersion': 'Latest version: {version}',
    'checkUpdates': 'Check updates',
    'checkingUpdates': 'Checking updates...',
    'openUpdate': 'Open update',
    'downloadUpdate': 'Download update',
    'downloadingUpdate': 'Downloading update...',
    'downloadProgress': 'Downloading update: {percent}%',
    'invalidUpdateUrl': 'The update link is not valid.',
    'couldNotDownloadUpdate': 'Could not download the update.',
    'couldNotInstallUpdate': 'Could not open the update installer.',
    'allowInstallPermission':
        'Allow Hoomy to install unknown apps, then try the update again.',
    'appUpToDate': 'You are using the latest version.',
    'updateAvailable': 'A newer version is available.',
    'updateRequired': 'This version should be updated before continuing.',
    'couldNotCheckUpdates': 'Could not check updates right now.',
    'updateHouseLocation': 'Update house location?',
    'updateHouseLocationBody':
        'Hoomy will use your current phone location as the saved house location.',
    'houseLocationUpdated':
        'House location updated from your current location.',
    'couldNotUpdateHouseLocation': 'Could not update house location.',
    'continuousUpdatesEnabled': 'Continuous updates enabled.',
    'couldNotEnableContinuousUpdates':
        'Could not enable continuous updates. Check location permission.',
    'gotIt': 'Got it',
    'houseSpecialNumberCopied': 'House special number copied',
    'addMissingItem': 'Add missing item',
    'itemOrNeed': 'Item or need',
    'noteOptional': 'Note optional',
    'emergencyRing': 'Emergency ring',
    'emergencyRingInfo': 'Treat like an urgent call-style alert.',
    'sendToSpecificMembers': 'Send to specific members',
    'noOtherMembersYet': 'No other members yet',
    'addMembersFirst':
        'Add family members first, or send the alert without selected recipients.',
    'sending': 'Sending...',
    'sendAlert': 'Send alert',
    'couldNotSaveAlert': 'Could not save alert',
    'addReminder': 'Add reminder',
    'reminderTitle': 'Reminder title',
    'isBirthday': 'Is birthday',
    'birthdayReminderInfo': 'Add a birthday reminder for one family member.',
    'birthdayFamilyMember': 'Birthday family member',
    'memberBirthdayTitle': '{name} birthday',
    'addReminderTitle': 'Add a reminder title.',
    'chooseBirthdayMember': 'Choose the birthday family member.',
    'saving': 'Saving...',
    'saveReminder': 'Save reminder',
    'ringTimes': 'Ring times',
    'addAnotherTime': 'Add another time',
    'editTime': 'Edit time',
    'removeTime': 'Remove time',
    'duplicateRingTime': 'This time is already added.',
    'repeatReminder': 'Repeat',
    'repeatOnce': 'Once',
    'repeatDaily': 'Daily',
    'repeatSelectedDays': 'Selected days',
    'chooseReminderDays': 'Choose at least one reminder day.',
    'deleteReminderQuestion': 'Delete reminder?',
    'deleteReminderBody': 'Delete "{title}" from reminders?',
    'couldNotSaveReminder': 'Could not save reminder',
    'birthdayReminder': 'Birthday reminder',
    'addFamilyMember': 'Add family member',
    'childName': 'Child name',
    'familyRelation': 'Family relation',
    'adding': 'Adding...',
    'enterChildAccountName': 'Enter the child account name.',
    'enterPhoneNumber': 'Enter the phone number.',
    'couldNotAddMember': 'Could not add member',
    'shortcutsTitle': 'Shortcuts',
    'familyChatValue': 'Family chat: {value}',
    'addShortcut': 'Add shortcut',
    'shortcutTitle': 'Shortcut title',
    'call': 'Call',
    'sms': 'SMS',
    'messageToSendInFamilyChat': 'Message to send in family chat',
    'completeShortcutFields': 'Complete the shortcut fields.',
    'couldNotSaveShortcut': 'Could not save shortcut',
    'houseQrCode': 'House QR code',
    'close': 'Close',
    'pointCameraAtQr': 'Point the camera at the house QR code.',
    'aboutSection': 'About {title}',
    'relationYou': 'You',
    'relationFather': 'Father',
    'relationMother': 'Mother',
    'relationBrother': 'Brother',
    'relationSister': 'Sister',
    'relationSon': 'Son',
    'relationDaughter': 'Daughter',
    'relationGrandfather': 'Grandfather',
    'relationGrandmother': 'Grandmother',
    'relationGrandson': 'Grandson',
    'relationGranddaughter': 'Granddaughter',
    'relationUncle': 'Uncle',
    'relationAunt': 'Aunt',
    'relationCousin': 'Cousin',
    'relationNephew': 'Nephew',
    'relationNiece': 'Niece',
    'relationGuest': 'Guest',
  },
  'ar': {
    'language': 'Ø§Ù„Ù„ØºØ©',
    'languageInfo': 'Ø§Ø®ØªØ± Ù„ØºØ© Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø¹Ù„Ù‰ Ù‡Ø°Ø§ Ø§Ù„Ù‡Ø§ØªÙ.',
    'english': 'Ø§Ù„Ø¥Ù†Ø¬Ù„ÙŠØ²ÙŠØ©',
    'arabic': 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©',
    'hoomy': 'Ù‡ÙˆÙ…ÙŠ',
    'gettingHomeReady': 'Ù†Ø¬Ù‡Ø² Ø¨ÙŠØªÙƒ...',
    'authSubtitle':
        'Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª Ø§Ù„Ø¨ÙŠØª ÙˆØ§Ù„ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø¹Ø§Ø¦Ù„ÙŠØ© ÙˆØ§Ù„ØªØ°ÙƒÙŠØ±Ø§Øª ÙˆØ§Ù„Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„Ø³Ø±ÙŠØ¹Ø© ÙÙŠ Ù…ÙƒØ§Ù† ÙˆØ§Ø­Ø¯.',
    'phone': 'Ø§Ù„Ù‡Ø§ØªÙ',
    'email': 'Ø§Ù„Ø¨Ø±ÙŠØ¯',
    'childAccountName': 'Ø§Ø³Ù… Ø­Ø³Ø§Ø¨ Ø§Ù„Ø·ÙÙ„',
    'yourName': 'Ø§Ø³Ù…Ùƒ',
    'phoneNumber': 'Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ',
    'emailAddress': 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
    'password': 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
    'forgotPassword': 'Ù†Ø³ÙŠØª ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±ØŸ',
    'signInAsChild': 'Ø§Ù„Ø¯Ø®ÙˆÙ„ ÙƒØ­Ø³Ø§Ø¨ Ø·ÙÙ„',
    'stillYoungChild': 'Ø·ÙÙ„ / Ù…Ø§ Ø²Ø§Ù„ ØµØºÙŠØ±Ø§',
    'useUniqueChildName': 'Ø§Ø³ØªØ®Ø¯Ù… Ø§Ø³Ù… Ø§Ù„Ø·ÙÙ„ Ø§Ù„ÙØ±ÙŠØ¯.',
    'noPhoneEmailChild':
        'Ù„Ø§ ÙŠØ­ØªØ§Ø¬ Ø¥Ù„Ù‰ Ù‡Ø§ØªÙ Ø£Ùˆ Ø¨Ø±ÙŠØ¯. ÙŠÙ…ÙƒÙ† Ù„Ø£Ø­Ø¯ Ø§Ù„ÙˆØ§Ù„Ø¯ÙŠÙ† Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø­Ø³Ø§Ø¨.',
    'connecting': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø§ØªØµØ§Ù„',
    'signIn': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
    'continue': 'Ù…ØªØ§Ø¨Ø¹Ø©',
    'createNewAccount': 'Ø¥Ù†Ø´Ø§Ø¡ Ø­Ø³Ø§Ø¨ Ø¬Ø¯ÙŠØ¯',
    'alreadyHaveAccount': 'Ù„Ø¯ÙŠÙƒ Ø­Ø³Ø§Ø¨ØŸ Ø³Ø¬Ù„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
    'resetPassword': 'Ø¥Ø¹Ø§Ø¯Ø© ØªØ¹ÙŠÙŠÙ† ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
    'resetRequestSent': 'ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø·Ù„Ø¨ Ø§Ù„ØªØ¹ÙŠÙŠÙ†. ÙŠØªÙ… Ø­ÙØ¸ ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ± Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©.',
    'resetting': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„ØªØ¹ÙŠÙŠÙ†',
    'home': 'Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©',
    'chat': 'Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø©',
    'calendar': 'Ø§Ù„ØªÙ‚ÙˆÙŠÙ…',
    'settings': 'Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª',
    'joinHouse': 'Ø§Ù†Ø¶Ù… Ù„Ù„Ø¨ÙŠØª',
    'createHouse': 'Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø¨ÙŠØª',
    'createNewHouse': 'Ø¥Ù†Ø´Ø§Ø¡ Ø¨ÙŠØª Ø¬Ø¯ÙŠØ¯',
    'defaultHouseName': 'Ø¨ÙŠØªÙ†Ø§',
    'couldNotCreateHouse': 'ØªØ¹Ø°Ø± Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø¨ÙŠØª',
    'chooseHouse': 'Ø§Ø®ØªÙŠØ§Ø± Ø§Ù„Ø¨ÙŠØª',
    'chooseHouseTitle': 'Ø£ÙŠ Ø¨ÙŠØª ØªØ±ÙŠØ¯ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¥Ù„ÙŠÙ‡ØŸ',
    'chooseHouseBody':
        'Ù‡Ø°Ø§ Ø§Ù„Ø­Ø³Ø§Ø¨ Ù…ÙˆØ¬ÙˆØ¯ ÙÙŠ Ø£ÙƒØ«Ø± Ù…Ù† Ø¨ÙŠØª. Ø§Ø®ØªØ± Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù†Ø´Ø· Ù„Ù‡Ø°Ù‡ Ø§Ù„Ø¬Ù„Ø³Ø©.',
    'chooseFromMyHouses': 'اختر من بيوتي',
    'joinAHouse': 'Ø§Ù„Ø§Ù†Ø¶Ù…Ø§Ù… Ø¥Ù„Ù‰ Ø¨ÙŠØª',
    'createYourHouse': 'Ø£Ù†Ø´Ø¦ Ø¨ÙŠØªÙƒ',
    'signOut': 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
    'create': 'Ø¥Ù†Ø´Ø§Ø¡',
    'join': 'Ø§Ù†Ø¶Ù…Ø§Ù…',
    'yourFamilyRole': 'Ø¯ÙˆØ±Ùƒ ÙÙŠ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'houseSpecialNumber': 'Ø±Ù‚Ù… Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ø®Ø§Øµ',
    'scanHouseQr': 'Ù…Ø³Ø­ Ø±Ù…Ø² Ø§Ù„Ø¨ÙŠØª',
    'houseName': 'Ø§Ø³Ù… Ø§Ù„Ø¨ÙŠØª',
    'addressOrNeighborhood': 'Ø§Ù„Ø¹Ù†ÙˆØ§Ù† Ø£Ùˆ Ø§Ù„Ø­ÙŠ',
    'allowHouseLocation': 'Ø§Ù„Ø³Ù…Ø§Ø­ Ø¨Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª',
    'usedOutsideMembers':
        'ÙŠØ³ØªØ®Ø¯Ù… Ù„Ø§Ø­Ù‚Ø§ Ù„ØªÙ†Ø¨ÙŠÙ‡ Ø£ÙØ±Ø§Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„Ù…ÙˆØ¬ÙˆØ¯ÙŠÙ† Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª Ø£ÙˆÙ„Ø§.',
    'currentLocation': 'Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø­Ø§Ù„ÙŠ',
    'gettingCurrentLocation': 'Ø¬Ø§Ø±ÙŠ Ø¬Ù„Ø¨ Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø­Ø§Ù„ÙŠ...',
    'noLocationAdded': 'Ù„Ù… ØªØªÙ… Ø¥Ø¶Ø§ÙØ© Ù…ÙˆÙ‚Ø¹',
    'enableLocation': 'ØªÙØ¹ÙŠÙ„ Ø§Ù„Ù…ÙˆÙ‚Ø¹',
    'enableLocationBody':
        'Ø´ØºÙ„ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¬Ù‡Ø§Ø²ØŒ Ø«Ù… Ø§Ø³Ù…Ø­ Ù„Ù‡ÙˆÙ…ÙŠ Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Ù…ÙˆÙ‚Ø¹Ùƒ Ø§Ù„Ø­Ø§Ù„ÙŠ.',
    'enableStatusLocationBody':
        'Ø´ØºÙ„ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¬Ù‡Ø§Ø²ØŒ Ø«Ù… Ø§Ø³Ù…Ø­ Ù„Ù‡ÙˆÙ…ÙŠ Ø¨ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„ØªÙƒ ÙÙŠ Ø§Ù„Ø¨ÙŠØª.',
    'enableHouseLocationBody':
        'Ø´ØºÙ„ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¬Ù‡Ø§Ø²ØŒ Ø«Ù… Ø§Ø³Ù…Ø­ Ù„Ù‡ÙˆÙ…ÙŠ Ø¨Ø­ÙØ¸ Ù…ÙˆÙ‚Ø¹ Ù‡Ø°Ø§ Ø§Ù„Ù‡Ø§ØªÙ ÙƒÙ…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª.',
    'enableAutoStatusLocationBody':
        'Ø´ØºÙ„ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¬Ù‡Ø§Ø²ØŒ Ø«Ù… Ø§Ø³Ù…Ø­ Ù„Ù‡ÙˆÙ…ÙŠ Ø¨ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„ØªÙƒ ÙÙŠ Ø§Ù„Ø¨ÙŠØª ØªÙ„Ù‚Ø§Ø¦ÙŠØ§.',
    'ok': 'Ø­Ø³Ù†Ø§',
    'couldNotGetLocation':
        'ØªØ¹Ø°Ø± Ø¬Ù„Ø¨ Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø­Ø§Ù„ÙŠ. ØªØ­Ù‚Ù‚ Ù…Ù† Ø®Ø¯Ù…Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹ ÙˆØ§Ù„ØµÙ„Ø§Ø­ÙŠØ©.',
    'currentLocationAdded': 'ØªÙ…Øª Ø¥Ø¶Ø§ÙØ© Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø­Ø§Ù„ÙŠ Ù„Ù‡Ø°Ø§ Ø§Ù„Ø¨ÙŠØª.',
    'joining': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø§Ù†Ø¶Ù…Ø§Ù…',
    'creating': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø¥Ù†Ø´Ø§Ø¡',
    'familyChat': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'noMessagesYet': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø±Ø³Ø§Ø¦Ù„ Ø¨Ø¹Ø¯',
    'messagePending': 'Ù‚ÙŠØ¯ Ø§Ù„Ø¥Ø±Ø³Ø§Ù„',
    'messageSent': 'ØªÙ… Ø§Ù„Ø¥Ø±Ø³Ø§Ù„',
    'messageReceived': 'ØªÙ… Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù…',
    'messageSeen': 'ØªÙ…Øª Ø§Ù„Ù…Ø´Ø§Ù‡Ø¯Ø©',
    'messageFailed': 'ÙØ´Ù„',
    'member': 'ÙØ±Ø¯',
    'messageTheFamily': 'Ø±Ø§Ø³Ù„ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'attachImage': 'Ø¥Ø±ÙØ§Ù‚ ØµÙˆØ±Ø©',
    'captureImage': 'Ø§Ù„ØªÙ‚Ø§Ø· ØµÙˆØ±Ø©',
    'saveImage': 'Ø­ÙØ¸ Ø§Ù„ØµÙˆØ±Ø©',
    'imageSavedToPhone': 'ØªÙ… Ø­ÙØ¸ Ø§Ù„ØµÙˆØ±Ø© ÙÙŠ Ø§Ù„Ù‡Ø§ØªÙ',
    'couldNotSaveImage': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„ØµÙˆØ±Ø©',
    'couldNotSendMessage': 'ØªØ¹Ø°Ø± Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
    'messageOptions': 'Ø®ÙŠØ§Ø±Ø§Øª Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
    'reply': 'Ø±Ø¯',
    'replyToYourMessage': 'Ø£Ø¶Ù Ù…ØªØ§Ø¨Ø¹Ø© Ù„Ø±Ø³Ø§Ù„ØªÙƒ',
    'replyToFamilyMessage': 'Ø±Ø¯ ÙÙŠ Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'replyingTo': 'Ø±Ø¯ Ø¹Ù„Ù‰ {name}',
    'cancelReply': 'Ø¥Ù„ØºØ§Ø¡ Ø§Ù„Ø±Ø¯',
    'edit': 'ØªØ¹Ø¯ÙŠÙ„',
    'editYourMessage': 'Ø­Ø¯Ù‘Ø« Ø§Ù„Ù†Øµ Ø§Ù„Ø°ÙŠ Ø£Ø±Ø³Ù„ØªÙ‡',
    'info': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª',
    'viewMessageInfo': 'Ø§Ø¹Ø±Ù Ù…Ù† Ø§Ø³ØªÙ„Ù…Ù‡Ø§ Ø£Ùˆ Ù‚Ø±Ø£Ù‡Ø§',
    'messageInfo': 'Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
    'sentAt': 'Ø£Ø±Ø³Ù„Øª ÙÙŠ {time}',
    'readBy': 'Ù‚Ø±Ø£Ù‡Ø§',
    'deliveredTo': 'ØªÙ… ØªØ³Ù„ÙŠÙ…Ù‡Ø§ Ø¥Ù„Ù‰',
    'read': 'ØªÙ…Øª Ø§Ù„Ù‚Ø±Ø§Ø¡Ø©',
    'delivered': 'ØªÙ… Ø§Ù„ØªØ³Ù„ÙŠÙ…',
    'notSeenYet': 'Ù„Ù… ÙŠÙ‚Ø±Ø£Ù‡Ø§ Ø£Ø­Ø¯ Ø¨Ø¹Ø¯.',
    'notDeliveredYet': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ ØªØ£ÙƒÙŠØ¯ ØªØ³Ù„ÙŠÙ… Ø¨Ø¹Ø¯.',
    'reactions': 'Ø§Ù„ØªÙØ§Ø¹Ù„Ø§Øª',
    'couldNotReactMessage': 'ØªØ¹Ø°Ø± ØªØ­Ø¯ÙŠØ« Ø§Ù„ØªÙØ§Ø¹Ù„',
    'edited': 'ØªÙ… Ø§Ù„ØªØ¹Ø¯ÙŠÙ„',
    'editingMessage': 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
    'cancelEdit': 'Ø¥Ù„ØºØ§Ø¡ Ø§Ù„ØªØ¹Ø¯ÙŠÙ„',
    'couldNotEditMessage': 'ØªØ¹Ø°Ø± ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ø±Ø³Ø§Ù„Ø©',
    'recordVoiceMessage': 'ØªØ³Ø¬ÙŠÙ„ Ø±Ø³Ø§Ù„Ø© ØµÙˆØªÙŠØ©',
    'holdToRecord': 'Ø§Ø¶ØºØ· Ù…Ø·ÙˆÙ„Ø§ Ù„Ù„ØªØ³Ø¬ÙŠÙ„',
    'sendVoiceMessage': 'Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ø³Ø§Ù„Ø© Ø§Ù„ØµÙˆØªÙŠØ©',
    'slideLeftToCancel': 'Ø§Ø³Ø­Ø¨ Ù„Ù„ÙŠØ³Ø§Ø± Ù„Ù„Ø¥Ù„ØºØ§Ø¡',
    'releaseToCancel': 'Ø§ØªØ±Ùƒ Ù„Ù„Ø¥Ù„ØºØ§Ø¡',
    'slideUpToLock': 'Ù‚ÙÙ„',
    'recordingLocked': 'ØªÙ… Ù‚ÙÙ„ Ø§Ù„ØªØ³Ø¬ÙŠÙ„',
    'stopRecording': 'Ø¥ÙŠÙ‚Ø§Ù Ø§Ù„ØªØ³Ø¬ÙŠÙ„',
    'voicePreview': 'Ù…Ø¹Ø§ÙŠÙ†Ø© Ø§Ù„Ø±Ø³Ø§Ù„Ø© Ø§Ù„ØµÙˆØªÙŠØ©',
    'playVoicePreview': 'ØªØ´ØºÙŠÙ„ Ù…Ø¹Ø§ÙŠÙ†Ø© Ø§Ù„ØµÙˆØª',
    'voiceMessageSeconds': 'Ø±Ø³Ø§Ù„Ø© ØµÙˆØªÙŠØ© â€¢ {seconds}Ø«',
    'playbackSpeed': 'Ø³Ø±Ø¹Ø© Ø§Ù„ØªØ´ØºÙŠÙ„',
    'microphonePermissionDenied': 'ØµÙ„Ø§Ø­ÙŠØ© Ø§Ù„Ù…ÙŠÙƒØ±ÙˆÙÙˆÙ† Ù…Ø·Ù„ÙˆØ¨Ø© Ù„Ù„ØªØ³Ø¬ÙŠÙ„.',
    'microphoneReadyHoldAgain':
        'Ø§Ù„Ù…ÙŠÙƒØ±ÙˆÙÙˆÙ† Ø¬Ø§Ù‡Ø². Ø§Ø¶ØºØ· Ù…Ø·ÙˆÙ„Ø§ Ø¹Ù„Ù‰ Ø§Ù„Ù…ÙŠÙƒØ±ÙˆÙÙˆÙ† Ù…Ø±Ø© Ø£Ø®Ø±Ù‰ Ù„Ù„ØªØ³Ø¬ÙŠÙ„.',
    'couldNotRecordMessage': 'ØªØ¹Ø°Ø± Ø¨Ø¯Ø¡ Ø§Ù„ØªØ³Ø¬ÙŠÙ„.',
    'couldNotSendVoiceMessage': 'ØªØ¹Ø°Ø± Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø±Ø³Ø§Ù„Ø© Ø§Ù„ØµÙˆØªÙŠØ©',
    'couldNotSendImageMessage': 'ØªØ¹Ø°Ø± Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„ØµÙˆØ±Ø©',
    'thisMonth': 'Ù‡Ø°Ø§ Ø§Ù„Ø´Ù‡Ø±',
    'needAlert': 'ØªÙ†Ø¨ÙŠÙ‡ Ø§Ø­ØªÙŠØ§Ø¬',
    'urgent': 'Ø¹Ø§Ø¬Ù„',
    'addMember': 'Ø¥Ø¶Ø§ÙØ© ÙØ±Ø¯',
    'quickActions': 'Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø³Ø±ÙŠØ¹Ø©',
    'quickActionsInfo':
        'Ø§Ø¬Ø¹Ù„ Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„Ù…ØªÙƒØ±Ø±Ø© Ù‚Ø±ÙŠØ¨Ø©ØŒ Ù…Ø«Ù„ Ø§Ù„Ø§ØªØµØ§Ù„ Ø¨Ø§Ù„Ø¨ÙŠØª Ø£Ùˆ Ø¥Ø±Ø³Ø§Ù„ Ø±Ø³Ø§Ù„Ø© Ø³Ø±ÙŠØ¹Ø©.',
    'add': 'Ø¥Ø¶Ø§ÙØ©',
    'needsAlerts': 'ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª',
    'needsAlertsInfo':
        'Ø´Ø§Ø±Ùƒ Ø§Ù„Ø£Ø´ÙŠØ§Ø¡ Ø§Ù„ØªÙŠ ÙŠØ­ØªØ§Ø¬Ù‡Ø§ Ø§Ù„Ø¨ÙŠØª Ù‚Ø¨Ù„ Ø£Ù† ÙŠÙ†Ø³Ø§Ù‡Ø§ Ø£Ø­Ø¯. Ø§Ø¬Ø¹Ù„Ù‡Ø§ Ø¹Ø§Ø¬Ù„Ø© Ø¹Ù†Ø¯ Ø§Ù„Ø­Ø§Ø¬Ø©.',
    'new': 'Ø¬Ø¯ÙŠØ¯',
    'cancel': 'Ø¥Ù„ØºØ§Ø¡',
    'clearSelection': 'Ù…Ø³Ø­ Ø§Ù„ØªØ­Ø¯ÙŠØ¯',
    'selectNeeds': 'ØªØ­Ø¯ÙŠØ¯ Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª',
    'boughtCount': 'ØªÙ… Ø§Ù„Ø¥Ù†Ø¬Ø§Ø² ({count})',
    'noMissingItems': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª Ù†Ø§Ù‚ØµØ© Ø§Ù„Ø¢Ù†.',
    'reminders': 'Ø§Ù„ØªØ°ÙƒÙŠØ±Ø§Øª',
    'remindersInfo': 'Ù…ÙƒØ§Ù† Ù…Ø´ØªØ±Ùƒ Ù„Ù…Ù‡Ø§Ù… Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© ÙˆØ§Ù„Ù…ÙˆØ§Ø¹ÙŠØ¯ ÙˆÙ„Ø­Ø¸Ø§Øª Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù…Ù‡Ù…Ø©.',
    'family': 'Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'familyInfo': 'Ø´Ø§Ù‡Ø¯ Ø£ÙØ±Ø§Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© ÙˆØµÙ„ØªÙ‡Ù… Ø¨Ùƒ ÙˆÙ…Ù† Ù‡Ùˆ Ø¯Ø§Ø®Ù„ Ø§Ù„Ø¨ÙŠØª Ø£Ùˆ Ø®Ø§Ø±Ø¬Ù‡.',
    'memberLocation': 'Ù…ÙˆÙ‚Ø¹ Ø§Ù„ÙØ±Ø¯',
    'viewMemberLocation': 'Ø¹Ø±Ø¶ Ù…ÙˆÙ‚Ø¹ Ø§Ù„ÙØ±Ø¯',
    'locationNotAvailable': 'Ø§Ù„Ù…ÙˆÙ‚Ø¹ ØºÙŠØ± Ù…ØªÙˆÙØ± Ø¨Ø¹Ø¯.',
    'locationNotAvailableBody': 'Ù‡Ø°Ø§ Ø§Ù„ÙØ±Ø¯ Ù„Ù… ÙŠØ´Ø§Ø±Ùƒ Ù…ÙˆÙ‚Ø¹Ø§ Ø­Ø§Ù„ÙŠØ§ Ù…Ù† Ù‡ÙˆÙ…ÙŠ Ø¨Ø¹Ø¯.',
    'latitude': 'Ø®Ø· Ø§Ù„Ø¹Ø±Ø¶',
    'longitude': 'Ø®Ø· Ø§Ù„Ø·ÙˆÙ„',
    'lastUpdated': 'Ø¢Ø®Ø± ØªØ­Ø¯ÙŠØ«',
    'notUpdatedYet': 'Ù„Ù… ÙŠØªÙ… Ø§Ù„ØªØ­Ø¯ÙŠØ« Ø¨Ø¹Ø¯',
    'openGoogleMaps': 'ÙØªØ­ Ø®Ø±Ø§Ø¦Ø· Google',
    'invite': 'Ø¯Ø¹ÙˆØ©',
    'helloName': 'Ù…Ø±Ø­Ø¨Ø§ØŒ {name}',
    'homeSummary':
        '{needs} Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª Ù…ÙØªÙˆØ­Ø©ØŒ {reminders} ØªØ°ÙƒÙŠØ±Ø§ØªØŒ {members} Ø£ÙØ±Ø§Ø¯.',
    'birthdayToday': 'Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯ Ø§Ù„ÙŠÙˆÙ…: {name}',
    'birthdaysToday': 'Ø£Ø¹ÙŠØ§Ø¯ Ù…ÙŠÙ„Ø§Ø¯ Ø§Ù„ÙŠÙˆÙ…: {names}',
    'outside': 'Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª',
    'inside': 'Ø¯Ø§Ø®Ù„ Ø§Ù„Ø¨ÙŠØª',
    'updatedOutside': 'ØªÙ… Ø§Ù„ØªØ­Ø¯ÙŠØ«: Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª.',
    'updatedInside': 'ØªÙ… Ø§Ù„ØªØ­Ø¯ÙŠØ«: Ø¯Ø§Ø®Ù„ Ø§Ù„Ø¨ÙŠØª.',
    'couldNotUpdateLocationStatus': 'ØªØ¹Ø°Ø± ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹.',
    'markSelectedNeedsBought': 'ØªØ­Ø¯ÙŠØ¯ Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª Ø§Ù„Ù…Ø®ØªØ§Ø±Ø© ÙƒÙ…Ù†Ø¬Ø²Ø©',
    'notifyFamily': 'Ø¥Ø¨Ù„Ø§Øº Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'notifying': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø¥Ø¨Ù„Ø§Øº...',
    'couldNotNotifyFamily': 'ØªØ¹Ø°Ø± Ø¥Ø¨Ù„Ø§Øº Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'quantityOptional': 'Ø§Ù„ÙƒÙ…ÙŠØ© Ø§Ø®ØªÙŠØ§Ø±ÙŠ',
    'priceOptional': 'Ø§Ù„Ø³Ø¹Ø± Ø§Ø®ØªÙŠØ§Ø±ÙŠ',
    'markAsBought': 'ØªØ­Ø¯ÙŠØ¯ {item} ÙƒÙ…Ù†Ø¬Ø²',
    'bought': 'ØªÙ…',
    'house': 'Ø§Ù„Ø¨ÙŠØª',
    'houseInfo':
        'Ù‡Ø°Ù‡ Ù…Ø³Ø§Ø­Ø© Ø¹Ø§Ø¦Ù„ØªÙƒ. Ø§Ø­ØªÙØ¸ Ø¨Ø¹Ù†ÙˆØ§Ù† Ø§Ù„Ø¨ÙŠØª ÙˆØ±Ù‚Ù…Ù‡ Ø§Ù„Ø®Ø§Øµ Ù„Ù„Ø£Ø´Ø®Ø§Øµ Ø§Ù„Ù…ÙˆØ«ÙˆÙ‚ÙŠÙ†.',
    'noAddressAdded': 'Ù„Ù… ØªØªÙ… Ø¥Ø¶Ø§ÙØ© Ø¹Ù†ÙˆØ§Ù†',
    'changeHouse': 'ØªØºÙŠÙŠØ± Ø§Ù„Ø¨ÙŠØª',
    'changeHouseSubtitle': 'Ø§Ù†Ø¶Ù… Ø¥Ù„Ù‰ Ø¨ÙŠØª Ø¢Ø®Ø± Ø¨Ø§Ù„Ø±Ù‚Ù… Ø§Ù„Ø®Ø§Øµ Ø£Ùˆ Ø±Ù…Ø² QR.',
    'changeHouseInfo':
        'Ø³ØªØ¨Ù‚Ù‰ ÙØ±Ø¯Ø§ ÙÙŠ Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù‚Ø¯ÙŠÙ…ØŒ Ù„ÙƒÙ† Ø­Ø§Ù„ØªÙƒ Ø³ØªØµØ¨Ø­ Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª Ø­ØªÙ‰ ØªØ¯Ø®Ù„ Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù†Ø´Ø· ÙˆØªØ­Ø¯Ø« Ù…ÙˆÙ‚Ø¹Ùƒ.',
    'changeHouseQuestion': 'ØªØºÙŠÙŠØ± Ø§Ù„Ø¨ÙŠØª Ø¥Ù„Ù‰ Ù‡Ø°Ø§ Ø§Ù„Ø¨ÙŠØªØŸ',
    'changeHouseConfirmBody':
        'Ø³ÙŠØ­ÙˆÙ„ Ù‡ÙˆÙ…ÙŠ Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù†Ø´Ø· Ø¥Ù„Ù‰ Ù‡Ø°Ø§ Ø§Ù„Ø±Ù‚Ù… Ø§Ù„Ø®Ø§Øµ. Ø³ØªØ¨Ù‚Ù‰ ÙÙŠ Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù‚Ø¯ÙŠÙ… ÙˆØ³ÙŠØªÙ… ØªØ­Ø¯ÙŠØ¯Ùƒ Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª Ø­ØªÙ‰ ÙŠØªÙ… ØªØ­Ø¯ÙŠØ« Ù…ÙˆÙ‚Ø¹Ùƒ.',
    'changingHouse': 'Ø¬Ø§Ø±ÙŠ ØªØºÙŠÙŠØ± Ø§Ù„Ø¨ÙŠØª...',
    'houseChanged': 'ØªÙ… ØªØºÙŠÙŠØ± Ø§Ù„Ø¨ÙŠØª. Ø­Ø§Ù„ØªÙƒ Ø§Ù„Ø¢Ù† Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª.',
    'enterHouseSpecialNumber': 'Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ø®Ø§Øµ.',
    'couldNotChangeHouse': 'ØªØ¹Ø°Ø± ØªØºÙŠÙŠØ± Ø§Ù„Ø¨ÙŠØª',
    'showQrCode': 'Ø¹Ø±Ø¶ Ø±Ù…Ø² QR',
    'copySpecialNumber': 'Ù†Ø³Ø® Ø§Ù„Ø±Ù‚Ù… Ø§Ù„Ø®Ø§Øµ',
    'location': 'Ø§Ù„Ù…ÙˆÙ‚Ø¹',
    'locationInfo':
        'ÙŠØ³Ø§Ø¹Ø¯ Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø¹Ù„Ù‰ Ù…Ø¹Ø±ÙØ© Ù…ØªÙ‰ ØªÙƒÙˆÙ† Ù‚Ø±ÙŠØ¨Ø§ Ù…Ù† Ø§Ù„Ø¨ÙŠØªØŒ ÙÙ‚Ø· Ø¹Ù†Ø¯Ù…Ø§ ØªØ³Ù…Ø­ Ø¨Ø°Ù„Ùƒ.',
    'notifications': 'Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',
    'about': 'Ø­ÙˆÙ„',
    'aboutInfo':
        'Ø²Ø§ÙˆÙŠØ© Ù‡Ø§Ø¯Ø¦Ø© Ù„ØªÙØ§ØµÙŠÙ„ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ ÙˆØ­Ø§Ù„Ø© Ø§Ù„Ø§ØªØµØ§Ù„ Ø§Ù„ÙÙˆØ±ÙŠ ÙˆÙ…ÙŠØ²Ø§Øª Ø§Ù„Ø¨ÙŠÙˆØª Ø§Ù„Ù…Ø³ØªÙ‚Ø¨Ù„ÙŠØ©.',
    'account': 'Ø§Ù„Ø­Ø³Ø§Ø¨',
    'accountInfo':
        'Ø£Ø¯Ø± Ø¬Ù„Ø³ØªÙƒ Ø¹Ù„Ù‰ Ù‡Ø°Ø§ Ø§Ù„Ø¬Ù‡Ø§Ø². ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬ ÙŠØ¨Ù‚ÙŠ Ø­Ø³Ø§Ø¨Ùƒ Ø¬Ø§Ù‡Ø²Ø§ Ù„Ù„Ù…Ø±Ø© Ø§Ù„Ù‚Ø§Ø¯Ù…Ø©.',
    'profile': 'Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    'editProfile': 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    'fullName': 'Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
    'birthday': 'Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'noPhoneAdded': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø±Ù‚Ù… Ù‡Ø§ØªÙ',
    'noEmailAdded': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø¨Ø±ÙŠØ¯ Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
    'tapToChooseBirthday': 'Ø§Ø¶ØºØ· Ù„Ø§Ø®ØªÙŠØ§Ø± Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'saveProfile': 'Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    'profileSaved': 'ØªÙ… Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    'couldNotSaveProfile': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    'nameRequired': 'Ø§Ù„Ø§Ø³Ù… Ù…Ø·Ù„ÙˆØ¨',
    'yourBirthday': 'Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯Ùƒ',
    'noBirthdayAdded': 'Ù„Ù… ØªØªÙ… Ø¥Ø¶Ø§ÙØ© Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯',
    'removeBirthday': 'Ø­Ø°Ù Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'birthdayRemoved': 'ØªÙ… Ø­Ø°Ù Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'birthdaySaved': 'ØªÙ… Ø­ÙØ¸ Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'couldNotSaveBirthday': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'houseLocation': 'Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª',
    'noHouseLocationSaved': 'Ù„Ù… ÙŠØªÙ… Ø­ÙØ¸ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª.',
    'houseLocationSaved': 'Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª Ù…Ø­ÙÙˆØ¸.',
    'myStatus': 'Ø­Ø§Ù„ØªÙŠ',
    'signInToUpdateStatus': 'Ø³Ø¬Ù„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ù„ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„ØªÙƒ.',
    'update': 'ØªØ­Ø¯ÙŠØ«',
    'autoUpdateStatus': 'ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø­Ø§Ù„Ø© ØªÙ„Ù‚Ø§Ø¦ÙŠØ§',
    'saveHouseLocationFirst': 'Ø§Ø­ÙØ¸ Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª Ø£ÙˆÙ„Ø§.',
    'refreshStatusEveryFew': 'ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„Ø© Ø¯Ø§Ø®Ù„/Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª ÙƒÙ„ Ø¹Ø¯Ø© Ø¯Ù‚Ø§Ø¦Ù‚.',
    'familyChatMessages': 'Ø±Ø³Ø§Ø¦Ù„ Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'notificationsInfo':
        'Ø§Ø®ØªØ± ØªØ­Ø¯ÙŠØ«Ø§Øª Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„ØªÙŠ ÙŠØ³ØªÙ„Ù…Ù‡Ø§ Ù‡Ø°Ø§ Ø§Ù„Ù‡Ø§ØªÙØŒ Ø¨Ù…Ø§ ÙÙŠÙ‡Ø§ Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø¹Ù†Ø¯Ù…Ø§ Ù„Ø§ ÙŠÙƒÙˆÙ† Ù‡ÙˆÙ…ÙŠ Ù…ÙØªÙˆØ­Ø§.',
    'showMissingItemAlerts': 'Ø¹Ø±Ø¶ ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø£ØºØ±Ø§Ø¶ Ø§Ù„Ù†Ø§Ù‚ØµØ©.',
    'useLongerEmergencySound': 'Ø§Ø³ØªØ®Ø¯Ø§Ù… ØµÙˆØª Ø§Ù„Ø·ÙˆØ§Ø±Ø¦ Ø§Ù„Ø£Ø·ÙˆÙ„.',
    'notifyChatNew': 'Ø¥Ø´Ø¹Ø§Ø± Ø¹Ù†Ø¯ ÙˆØ¬ÙˆØ¯ Ø¬Ø¯ÙŠØ¯ ÙÙŠ Ø§Ù„Ù…Ø­Ø§Ø¯Ø«Ø©.',
    'pushStatus': 'Ø­Ø§Ù„Ø© Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',
    'needAlertsSetting': 'ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª',
    'emergencyAlerts': 'ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø§Ù„Ø·ÙˆØ§Ø±Ø¦',
    'emergencyAlertCount': '{count} ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø·ÙˆØ§Ø±Ø¦',
    'shortcuts': 'Ø§Ù„Ø§Ø®ØªØµØ§Ø±Ø§Øª',
    'shortcutsInfo':
        'Ø§Ø¬Ø¹Ù„ Ø±ÙˆØªÙŠÙ†Ø§Øª Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø§Ù„ØµØºÙŠØ±Ø© Ø£Ø³Ø±Ø¹ Ø¨Ø§Ø®ØªØµØ§Ø±Ø§Øª Ø´Ø®ØµÙŠØ© Ù„Ù„Ø§ØªØµØ§Ù„ ÙˆØ§Ù„Ø±Ø³Ø§Ø¦Ù„ ÙˆØ§Ù„Ù…Ø­Ø§Ø¯Ø«Ø©.',
    'noShortcutsYet': 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø§Ø®ØªØµØ§Ø±Ø§Øª Ø¨Ø¹Ø¯',
    'updateShortcut': 'ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø§Ø®ØªØµØ§Ø±',
    'deleteShortcut': 'Ø­Ø°Ù Ø§Ù„Ø§Ø®ØªØµØ§Ø±',
    'updateReminder': 'ØªØ­Ø¯ÙŠØ« Ø§Ù„ØªØ°ÙƒÙŠØ±',
    'deleteReminder': 'Ø­Ø°Ù Ø§Ù„ØªØ°ÙƒÙŠØ±',
    'autoMembersOutside': 'ØªÙ„Ù‚Ø§Ø¦ÙŠ: Ø§Ù„Ø£ÙØ±Ø§Ø¯ Ø®Ø§Ø±Ø¬ Ø§Ù„Ø¨ÙŠØª',
    'requestFailed': 'ÙØ´Ù„ Ø§Ù„Ø·Ù„Ø¨',
    'deleteShortcutQuestion': 'Ø­Ø°Ù Ø§Ù„Ø§Ø®ØªØµØ§Ø±ØŸ',
    'deleteShortcutBody': 'Ø­Ø°Ù "{label}" Ù…Ù† Ø§Ø®ØªØµØ§Ø±Ø§ØªÙƒØŸ',
    'delete': 'Ø­Ø°Ù',
    'couldNotDeleteShortcut': 'ØªØ¹Ø°Ø± Ø­Ø°Ù Ø§Ù„Ø§Ø®ØªØµØ§Ø±',
    'viewAll': 'Ø¹Ø±Ø¶ Ø§Ù„ÙƒÙ„',
    'futureHouseDiscovery': 'Ø§Ø³ØªÙƒØ´Ø§Ù Ø¨ÙŠÙˆØª Ù…Ø³ØªÙ‚Ø¨Ù„Ø§',
    'privateHousesNow': 'Ø§Ù„Ø¨ÙŠÙˆØª Ø®Ø§ØµØ© Ø§Ù„Ø¢Ù†ØŒ ÙˆØ¬Ø§Ù‡Ø²Ø© Ù„Ù„ØªÙˆØ³Ø¹ Ù„Ø§Ø­Ù‚Ø§.',
    'realtimeBackend': 'Ø§Ù„Ø®Ø§Ø¯Ù… Ø§Ù„ÙÙˆØ±ÙŠ',
    'restSocketEnabled': 'REST Ùˆ Socket.IO Ù…ÙØ¹Ù„Ø© Ù„Ù„Ù…Ø²Ø§Ù…Ù†Ø©.',
    'aboutHoomy': 'Ø­ÙˆÙ„ Ù‡ÙˆÙ…ÙŠ',
    'aboutHoomyBody':
        'ÙŠØ³Ø§Ø¹Ø¯ Ù‡ÙˆÙ…ÙŠ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø¹Ù„Ù‰ ØªØ±ØªÙŠØ¨ Ø´Ø¤ÙˆÙ† Ø§Ù„Ø¨ÙŠØª Ù…Ø¹Ø§: Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª ÙˆØ§Ù„ØªÙ†Ø¨ÙŠÙ‡Ø§Øª ÙˆØ§Ù„ØªØ°ÙƒÙŠØ±Ø§Øª ÙˆØ§Ù„Ù…Ø­Ø§Ø¯Ø«Ø© ÙˆØ­Ø§Ù„Ø© Ø§Ù„Ù…ÙˆÙ‚Ø¹ ÙˆØ§Ù„Ø¥Ø¬Ø±Ø§Ø¡Ø§Øª Ø§Ù„Ø³Ø±ÙŠØ¹Ø© ÙÙŠ Ù…ÙƒØ§Ù† Ù‡Ø§Ø¯Ø¦ ÙˆØ§Ø­Ø¯.',
    'aboutNeedsTitle': 'Ø§Ø­ØªÙŠØ§Ø¬Ø§Øª Ø§Ù„Ø¨ÙŠØª',
    'aboutNeedsBody': 'Ø£Ø¶Ù Ø§Ù„Ø£ØºØ±Ø§Ø¶ Ø§Ù„Ù†Ø§Ù‚ØµØ© ÙˆØ£Ø®Ø¨Ø± Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø¹Ù†Ø¯Ù…Ø§ ÙŠØ´ØªØ±ÙŠÙ‡Ø§ Ø£Ø­Ø¯.',
    'aboutAlertsTitle': 'ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø°ÙƒÙŠØ©',
    'aboutAlertsBody': 'Ø£Ø±Ø³Ù„ ØªÙ†Ø¨ÙŠÙ‡Ø§Øª Ø¹Ø§Ø¯ÙŠØ© Ø£Ùˆ Ø·Ø§Ø±Ø¦Ø© Ù„Ù„Ø¬Ù…ÙŠØ¹ Ø£Ùˆ Ù„Ø£ÙØ±Ø§Ø¯ Ù…Ø­Ø¯Ø¯ÙŠÙ†.',
    'aboutChatTitle': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'aboutChatBody': 'Ø§Ø¬Ø¹Ù„ Ø±Ø³Ø§Ø¦Ù„ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© ÙˆØªØ­Ø¯ÙŠØ«Ø§Øª Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ø¨Ø³ÙŠØ·Ø© ÙÙŠ Ù†ÙØ³ Ø§Ù„Ù…ÙƒØ§Ù†.',
    'aboutCalendarTitle': 'ØªÙ‚ÙˆÙŠÙ… Ù…Ø´ØªØ±Ùƒ',
    'aboutCalendarBody':
        'Ø´Ø§Ù‡Ø¯ Ø§Ù„ØªØ°ÙƒÙŠØ±Ø§Øª ÙˆØ£Ø¹ÙŠØ§Ø¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯ ÙˆØ£Ø­Ø¯Ø§Ø« Ø§Ù„Ø¨ÙŠØª ÙÙŠ ØªÙ‚ÙˆÙŠÙ… ÙˆØ§Ø¶Ø­.',
    'appVersion': 'Ø¥ØµØ¯Ø§Ø± Ø§Ù„ØªØ·Ø¨ÙŠÙ‚',
    'currentVersion': 'Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ø§Ù„Ø­Ø§Ù„ÙŠ: {version}',
    'latestVersion': 'Ø¢Ø®Ø± Ø¥ØµØ¯Ø§Ø±: {version}',
    'checkUpdates': 'Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„ØªØ­Ø¯ÙŠØ«Ø§Øª',
    'checkingUpdates': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„ØªØ­Ø¯ÙŠØ«Ø§Øª...',
    'openUpdate': 'ÙØªØ­ Ø§Ù„ØªØ­Ø¯ÙŠØ«',
    'downloadUpdate': 'ØªØ­Ù…ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«',
    'downloadingUpdate': 'Ø¬Ø§Ø±ÙŠ ØªØ­Ù…ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«...',
    'downloadProgress': 'Ø¬Ø§Ø±ÙŠ ØªØ­Ù…ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«: {percent}%',
    'invalidUpdateUrl': 'Ø±Ø§Ø¨Ø· Ø§Ù„ØªØ­Ø¯ÙŠØ« ØºÙŠØ± ØµØ§Ù„Ø­.',
    'couldNotDownloadUpdate': 'ØªØ¹Ø°Ø± ØªØ­Ù…ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«.',
    'couldNotInstallUpdate': 'ØªØ¹Ø°Ø± ÙØªØ­ Ù…Ø«Ø¨Øª Ø§Ù„ØªØ­Ø¯ÙŠØ«.',
    'allowInstallPermission':
        'Ø§Ø³Ù…Ø­ Ù„Ù‡ÙˆÙ…ÙŠ Ø¨ØªØ«Ø¨ÙŠØª Ø§Ù„ØªØ·Ø¨ÙŠÙ‚Ø§Øª ØºÙŠØ± Ø§Ù„Ù…Ø¹Ø±ÙˆÙØ©ØŒ Ø«Ù… Ø­Ø§ÙˆÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ« Ù…Ø±Ø© Ø£Ø®Ø±Ù‰.',
    'appUpToDate': 'Ø£Ù†Øª ØªØ³ØªØ®Ø¯Ù… Ø¢Ø®Ø± Ø¥ØµØ¯Ø§Ø±.',
    'updateAvailable': 'ÙŠÙˆØ¬Ø¯ Ø¥ØµØ¯Ø§Ø± Ø£Ø­Ø¯Ø«.',
    'updateRequired': 'ÙŠØ¬Ø¨ ØªØ­Ø¯ÙŠØ« Ù‡Ø°Ø§ Ø§Ù„Ø¥ØµØ¯Ø§Ø± Ù‚Ø¨Ù„ Ø§Ù„Ù…ØªØ§Ø¨Ø¹Ø©.',
    'couldNotCheckUpdates': 'ØªØ¹Ø°Ø± Ø§Ù„ØªØ­Ù‚Ù‚ Ù…Ù† Ø§Ù„ØªØ­Ø¯ÙŠØ«Ø§Øª Ø§Ù„Ø¢Ù†.',
    'updateHouseLocation': 'ØªØ­Ø¯ÙŠØ« Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØªØŸ',
    'updateHouseLocationBody':
        'Ø³ÙŠØ³ØªØ®Ø¯Ù… Ù‡ÙˆÙ…ÙŠ Ù…ÙˆÙ‚Ø¹ Ù‡Ø§ØªÙÙƒ Ø§Ù„Ø­Ø§Ù„ÙŠ ÙƒÙ…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ù…Ø­ÙÙˆØ¸.',
    'houseLocationUpdated': 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª Ù…Ù† Ù…ÙˆÙ‚Ø¹Ùƒ Ø§Ù„Ø­Ø§Ù„ÙŠ.',
    'couldNotUpdateHouseLocation': 'ØªØ¹Ø°Ø± ØªØ­Ø¯ÙŠØ« Ù…ÙˆÙ‚Ø¹ Ø§Ù„Ø¨ÙŠØª.',
    'continuousUpdatesEnabled': 'ØªÙ… ØªÙØ¹ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«Ø§Øª Ø§Ù„Ù…Ø³ØªÙ…Ø±Ø©.',
    'couldNotEnableContinuousUpdates':
        'ØªØ¹Ø°Ø± ØªÙØ¹ÙŠÙ„ Ø§Ù„ØªØ­Ø¯ÙŠØ«Ø§Øª Ø§Ù„Ù…Ø³ØªÙ…Ø±Ø©. ØªØ­Ù‚Ù‚ Ù…Ù† ØµÙ„Ø§Ø­ÙŠØ© Ø§Ù„Ù…ÙˆÙ‚Ø¹.',
    'gotIt': 'ÙÙ‡Ù…Øª',
    'houseSpecialNumberCopied': 'ØªÙ… Ù†Ø³Ø® Ø±Ù‚Ù… Ø§Ù„Ø¨ÙŠØª Ø§Ù„Ø®Ø§Øµ',
    'addMissingItem': 'Ø¥Ø¶Ø§ÙØ© ØºØ±Ø¶ Ù†Ø§Ù‚Øµ',
    'itemOrNeed': 'Ø§Ù„ØºØ±Ø¶ Ø£Ùˆ Ø§Ù„Ø§Ø­ØªÙŠØ§Ø¬',
    'noteOptional': 'Ø§Ù„Ù…Ù„Ø§Ø­Ø¸Ø© Ø§Ø®ØªÙŠØ§Ø±ÙŠ',
    'emergencyRing': 'Ø±Ù†ÙŠÙ† Ø·ÙˆØ§Ø±Ø¦',
    'emergencyRingInfo': 'ÙŠØ¹Ø§Ù…Ù„ ÙƒØªÙ†Ø¨ÙŠÙ‡ Ø¹Ø§Ø¬Ù„ Ø¨Ø£Ø³Ù„ÙˆØ¨ Ø§ØªØµØ§Ù„.',
    'sendToSpecificMembers': 'Ø§Ù„Ø¥Ø±Ø³Ø§Ù„ Ø¥Ù„Ù‰ Ø£ÙØ±Ø§Ø¯ Ù…Ø­Ø¯Ø¯ÙŠÙ†',
    'noOtherMembersYet': 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø£ÙØ±Ø§Ø¯ Ø¢Ø®Ø±ÙˆÙ† Ø¨Ø¹Ø¯',
    'addMembersFirst':
        'Ø£Ø¶Ù Ø£ÙØ±Ø§Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© Ø£ÙˆÙ„Ø§ØŒ Ø£Ùˆ Ø£Ø±Ø³Ù„ Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡ Ø¨Ø¯ÙˆÙ† ØªØ­Ø¯ÙŠØ¯ Ù…Ø³ØªÙ„Ù…ÙŠÙ†.',
    'sending': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø¥Ø±Ø³Ø§Ù„...',
    'sendAlert': 'Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡',
    'couldNotSaveAlert': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡',
    'addReminder': 'Ø¥Ø¶Ø§ÙØ© ØªØ°ÙƒÙŠØ±',
    'reminderTitle': 'Ø¹Ù†ÙˆØ§Ù† Ø§Ù„ØªØ°ÙƒÙŠØ±',
    'isBirthday': 'Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯',
    'birthdayReminderInfo': 'Ø£Ø¶Ù ØªØ°ÙƒÙŠØ± Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯ Ù„Ø£Ø­Ø¯ Ø£ÙØ±Ø§Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©.',
    'birthdayFamilyMember': 'ÙØ±Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© ØµØ§Ø­Ø¨ Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯',
    'memberBirthdayTitle': 'Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯ {name}',
    'addReminderTitle': 'Ø£Ø¶Ù Ø¹Ù†ÙˆØ§Ù†Ø§ Ù„Ù„ØªØ°ÙƒÙŠØ±.',
    'chooseBirthdayMember': 'Ø§Ø®ØªØ± ÙØ±Ø¯ Ø§Ù„Ø¹Ø§Ø¦Ù„Ø© ØµØ§Ø­Ø¨ Ø¹ÙŠØ¯ Ø§Ù„Ù…ÙŠÙ„Ø§Ø¯.',
    'saving': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø­ÙØ¸...',
    'saveReminder': 'Ø­ÙØ¸ Ø§Ù„ØªØ°ÙƒÙŠØ±',
    'ringTimes': 'Ø£ÙˆÙ‚Ø§Øª Ø§Ù„ØªÙ†Ø¨ÙŠÙ‡',
    'addAnotherTime': 'Ø¥Ø¶Ø§ÙØ© ÙˆÙ‚Øª Ø¢Ø®Ø±',
    'editTime': 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„ÙˆÙ‚Øª',
    'removeTime': 'Ø­Ø°Ù Ø§Ù„ÙˆÙ‚Øª',
    'duplicateRingTime': 'Ù‡Ø°Ø§ Ø§Ù„ÙˆÙ‚Øª Ù…Ø¶Ø§Ù Ø¨Ø§Ù„ÙØ¹Ù„.',
    'repeatReminder': 'Ø§Ù„ØªÙƒØ±Ø§Ø±',
    'repeatOnce': 'Ù…Ø±Ø© ÙˆØ§Ø­Ø¯Ø©',
    'repeatDaily': 'ÙŠÙˆÙ…ÙŠØ§',
    'repeatSelectedDays': 'Ø£ÙŠØ§Ù… Ù…Ø­Ø¯Ø¯Ø©',
    'chooseReminderDays': 'Ø§Ø®ØªØ± ÙŠÙˆÙ…Ø§ ÙˆØ§Ø­Ø¯Ø§ Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„ Ù„Ù„ØªØ°ÙƒÙŠØ±.',
    'deleteReminderQuestion': 'Ø­Ø°Ù Ø§Ù„ØªØ°ÙƒÙŠØ±ØŸ',
    'deleteReminderBody': 'Ø­Ø°Ù "{title}" Ù…Ù† Ø§Ù„ØªØ°ÙƒÙŠØ±Ø§ØªØŸ',
    'couldNotSaveReminder': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„ØªØ°ÙƒÙŠØ±',
    'birthdayReminder': 'ØªØ°ÙƒÙŠØ± Ø¹ÙŠØ¯ Ù…ÙŠÙ„Ø§Ø¯',
    'addFamilyMember': 'Ø¥Ø¶Ø§ÙØ© ÙØ±Ø¯ Ù…Ù† Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'childName': 'Ø§Ø³Ù… Ø§Ù„Ø·ÙÙ„',
    'familyRelation': 'ØµÙ„Ø© Ø§Ù„Ù‚Ø±Ø§Ø¨Ø©',
    'adding': 'Ø¬Ø§Ø±ÙŠ Ø§Ù„Ø¥Ø¶Ø§ÙØ©...',
    'enterChildAccountName': 'Ø£Ø¯Ø®Ù„ Ø§Ø³Ù… Ø­Ø³Ø§Ø¨ Ø§Ù„Ø·ÙÙ„.',
    'enterPhoneNumber': 'Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ.',
    'couldNotAddMember': 'ØªØ¹Ø°Ø± Ø¥Ø¶Ø§ÙØ© Ø§Ù„ÙØ±Ø¯',
    'shortcutsTitle': 'Ø§Ù„Ø§Ø®ØªØµØ§Ø±Ø§Øª',
    'familyChatValue': 'Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©: {value}',
    'addShortcut': 'Ø¥Ø¶Ø§ÙØ© Ø§Ø®ØªØµØ§Ø±',
    'shortcutTitle': 'Ø¹Ù†ÙˆØ§Ù† Ø§Ù„Ø§Ø®ØªØµØ§Ø±',
    'call': 'Ø§ØªØµØ§Ù„',
    'sms': 'Ø±Ø³Ø§Ù„Ø©',
    'messageToSendInFamilyChat': 'Ø§Ù„Ø±Ø³Ø§Ù„Ø© Ø§Ù„ØªÙŠ Ø³ØªØ±Ø³Ù„ ÙÙŠ Ù…Ø­Ø§Ø¯Ø«Ø© Ø§Ù„Ø¹Ø§Ø¦Ù„Ø©',
    'completeShortcutFields': 'Ø£ÙƒÙ…Ù„ Ø­Ù‚ÙˆÙ„ Ø§Ù„Ø§Ø®ØªØµØ§Ø±.',
    'couldNotSaveShortcut': 'ØªØ¹Ø°Ø± Ø­ÙØ¸ Ø§Ù„Ø§Ø®ØªØµØ§Ø±',
    'houseQrCode': 'Ø±Ù…Ø² QR Ù„Ù„Ø¨ÙŠØª',
    'close': 'Ø¥ØºÙ„Ø§Ù‚',
    'pointCameraAtQr': 'ÙˆØ¬Ù‡ Ø§Ù„ÙƒØ§Ù…ÙŠØ±Ø§ Ø¥Ù„Ù‰ Ø±Ù…Ø² QR Ø§Ù„Ø®Ø§Øµ Ø¨Ø§Ù„Ø¨ÙŠØª.',
    'aboutSection': 'Ø­ÙˆÙ„ {title}',
    'relationYou': 'Ø£Ù†Øª',
    'relationFather': 'Ø§Ù„Ø£Ø¨',
    'relationMother': 'Ø§Ù„Ø£Ù…',
    'relationBrother': 'Ø§Ù„Ø£Ø®',
    'relationSister': 'Ø§Ù„Ø£Ø®Øª',
    'relationSon': 'Ø§Ù„Ø§Ø¨Ù†',
    'relationDaughter': 'Ø§Ù„Ø§Ø¨Ù†Ø©',
    'relationGrandfather': 'Ø§Ù„Ø¬Ø¯',
    'relationGrandmother': 'Ø§Ù„Ø¬Ø¯Ø©',
    'relationGrandson': 'Ø§Ù„Ø­ÙÙŠØ¯',
    'relationGranddaughter': 'Ø§Ù„Ø­ÙÙŠØ¯Ø©',
    'relationUncle': 'Ø§Ù„Ø¹Ù…',
    'relationAunt': 'Ø§Ù„Ø¹Ù…Ø©',
    'relationCousin': 'Ø§Ù„Ù‚Ø±ÙŠØ¨',
    'relationNephew': 'Ø§Ø¨Ù† Ø§Ù„Ø£Ø®',
    'relationNiece': 'Ø¨Ù†Øª Ø§Ù„Ø£Ø®',
    'relationGuest': 'Ø¶ÙŠÙ',
  },
};
